services:
  - type: web
    runtime: docker
    name: arwa-baqir
    plan: free
    branch: main
    rootDir: .
    dockerCommand: bash start.sh
    repo: https://github.com/mybot555/web.git
    region: frankfurt
    envVars:
      - key: API_ID
        value: 18109107
      - key: API_HASH
        value: e6afc7383da3a10fa16a0a9675c3e037
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: TZ
        value: Asia/Baghdad
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

databases:
  - name: postgres
    plan: free
    region: frankfurt
